# Generated by Django 4.2.8 on 2023-12-09 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="PokerSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_backlog", models.TextField()),
                ("product_backlog_file", models.FileField(upload_to="files")),
                (
                    "mode",
                    models.CharField(
                        choices=[("strict", "Strict"), ("medium", "Moyen"), ("median", "Median")],
                        default="strict",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Créée"), ("started", "Commencée"), ("finished", "Terminée")],
                        default="created",
                        max_length=10,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poker_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("story_points", models.IntegerField(blank=True, null=True)),
                (
                    "poker_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stories", to="core.pokersession"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vote", models.IntegerField()),
                (
                    "poker_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="core.pokersession"
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="core.story"
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="core.participant"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="participant",
            name="poker_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="core.pokersession"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="participants", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
