# Generated by Django 4.2.8 on 2023-12-17 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokersession",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="poker_sessions", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="poker_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="core.pokersession"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="participants", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="messages",
            name="poker_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="core.pokersession"
            ),
        ),
        migrations.AddField(
            model_name="messages",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="core.participant"
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="poker_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="features", to="core.pokersession"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together={("poker_session", "user")},
        ),
    ]
