# Generated by Django 4.2.8 on 2023-12-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_pokersession_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokersession",
            name="feature_field_name",
            field=models.CharField(default="items", max_length=50, verbose_name="Nom du champ des features"),
        ),
        migrations.AlterField(
            model_name="pokersession",
            name="product_backlog_file",
            field=models.FileField(upload_to="files", verbose_name="Fichier du backlog"),
        ),
        migrations.AlterField(
            model_name="story",
            name="story_points",
            field=models.IntegerField(default=0),
        ),
    ]
