# Generated by Django 4.2.8 on 2023-12-09 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_pokersession_feature_field_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(default="")),
                (
                    "poker_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="features", to="core.pokersession"
                    ),
                ),
            ],
        ),
    ]
