# Generated by Django 4.2.8 on 2023-12-09 10:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_remove_vote_story_feature_story_points_feature_voted_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together={("poker_session", "user")},
        ),
    ]
