# Generated by Django 4.2.8 on 2023-12-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="cafe",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vote",
            name="interro",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("designation", models.IntegerField(default=1)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tours", to="core.feature"
                    ),
                ),
                (
                    "poker_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tours", to="core.pokersession"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vote",
            name="tour",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="core.tour"
            ),
            preserve_default=False,
        ),
    ]
