# Generated by Django 4.2.8 on 2023-12-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_vote_cafe_vote_interro_tour_vote_tour"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokersession",
            name="players",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="pokersession",
            name="mode",
            field=models.CharField(
                choices=[("strict", "Strict"), ("medium", "Moyen")], default="strict", max_length=10
            ),
        ),
    ]
